# Generated by Django 4.2.7 on 2023-11-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_usermodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModels',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, default='static/images/Avatar (2).png', null=True, upload_to='images/'),
        ),
    ]
