# Generated by Django 4.2.7 on 2023-11-15 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usermodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='defult_img', null=True, upload_to='images/')),
                ('price', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='UserModels',
        ),
    ]
